### ISSUE TITLE
Class 'AlgoliaSearch\Client' not found

### ISSUE THREAD

**Issue by applyACS** [nicolasbeauvais/nova-algolia-card#2]
Do you still maintain this package?

I'm using:
"laravel/framework": "5.8.*",
"laravel/scout": "^7.1",
"algolia/algoliasearch-client-php": "^2.2",
"algolia/scout-extended": "^1.6",

Got this error on your package: "Class 'AlgoliaSearch\Client' not found"

**Comment by julienbourdeau** [comment]
Indeed, this was removed in Algolia client v2. Let me try to open a PR

**Comment by julienbourdeau** [comment]
If you still have this issue, could you try this PR? https://github.com/nicolasbeauvais/nova-algolia-card/pull/3
